- name: Deploy Kubernetes app with variable number of replicas
  hosts: localhost
  become: true
  vars:
    build: "{{ lookup('env', 'build') | default(1) }}"
  tasks:
    - name: Render Kubernetes manifest template
      template:
        src: kube.yaml
        dest: /tmp/deployment.yaml
        mode: '0644'

    - name: Apply Kubernetes manifest
      command: kubectl apply -f /tmp/deployment.yaml
